timezone: Asia/Shanghai
logger:
  console:
portlet:
  port: {{PORT}}
  version: "0.5.0"
  name: standalone
  layout: main
  language: cn
  redirects:
    '/': 'menu://main'
    '/users' : 'menu://main/settings/users'
  uploadDir: '{{STORAGE_ROOT}}/uploads'
  uploadMaxFileSize: 1G
  passport:
    jwt:
      expiration: 24h
  plugins:
    - '@vimesh/portlet-helper-es5'
    - '@vimesh/portlet-helper-faicon'
    - '@vimesh/portlet-helper-obfuscate'
    - '@vimesh/portlet-helper-tailwind'
    - '@vimesh/portlet-plugin-health'
    - '@vimesh/portlet-plugin-vue'
    - '@vimesh/portlet-plugin-storage'
  handlebars:
    settings:
      #tailwindCssFile: '{{ROOT}}/public/tailwind@2.2.7.min.css'