logger:
  level: debug
portlet:
  mock: true
  debug: true
  compress: false
  logRoutes: true
  logRequests: true
  storages:
    avatar: 
      type: local
      options:
        root: '{{STORAGE_ROOT}}/storage'
      bucket: 'main'
      prefix: 'avatar/'
      cacheDir: '{{STORAGE_ROOT}}/cache'